# fly.toml app configuration file generated for steexp-v2-beta on 2023-08-21T16:13:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "steexp-v2-beta"
primary_region = "sin"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 75
soft_limit = 50

[services.concurrency]
hard_limit = 75
soft_limit = 50
type = "connections"

[checks]
[checks.status]
port = 3000
type = "http"
interval = "60s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/healthcheck"
protocol = "http"
tls_skip_verify = false
